export const PIECES = [
  { id: 0, name: "NEON KIRA #001", accent: "#ff00aa", hair: "#ff66ee", eyes: "#00ffff", skin: "#f8c8b0", traits: [{ t: "Hair", v: "Cyber Twin Tails" }, { t: "Eyes", v: "Heterochromia Glow" }, { t: "Outfit", v: "Neon Hoodie + Jacket" }, { t: "Accessory", v: "VR Visor" }, { t: "Bg", v: "Tokyo Night Rain" }, { t: "Rarity", v: "Legendary" }] },
  { id: 1, name: "SHADOW RYU #002", accent: "#00ffcc", hair: "#222233", eyes: "#ff3366", skin: "#e8b080", traits: [{ t: "Hair", v: "Undercut Samurai" }, { t: "Eyes", v: "Scarred Crimson" }, { t: "Outfit", v: "Torn Kimono Jacket" }, { t: "Accessory", v: "Katana Sheath" }, { t: "Bg", v: "Neon Dojo" }, { t: "Rarity", v: "Mythic" }] },
  { id: 2, name: "SAKURA NOVA #003", accent: "#ff99ff", hair: "#ff4488", eyes: "#88ffff", skin: "#ffe0c0", traits: [{ t: "Hair", v: "Sakura Bangs" }, { t: "Eyes", v: "Star Pupils" }, { t: "Outfit", v: "Cherry Kimono Hoodie" }, { t: "Accessory", v: "Floating Petals" }, { t: "Bg", v: "Blooming Shrine" }, { t: "Rarity", v: "Legendary" }] },
  { id: 3, name: "MECHA LUNA #004", accent: "#00aaff", hair: "#aaccff", eyes: "#ffdd00", skin: "#d0e0ff", traits: [{ t: "Hair", v: "Holo Bob" }, { t: "Eyes", v: "Mech Scanner" }, { t: "Outfit", v: "Pilot Exo-Suit" }, { t: "Accessory", v: "Neural Crown" }, { t: "Bg", v: "Orbital Station" }, { t: "Rarity", v: "Epic" }] },
  { id: 4, name: "ONI BLAZE #005", accent: "#ff4400", hair: "#ff8800", eyes: "#ffff66", skin: "#aa6644", traits: [{ t: "Hair", v: "Flame Horns" }, { t: "Eyes", v: "Inferno Glow" }, { t: "Outfit", v: "Street Oni Jacket" }, { t: "Accessory", v: "Demon Mask" }, { t: "Bg", v: "Volcano City" }, { t: "Rarity", v: "Mythic" }] },
  { id: 5, name: "KITSUNE ECHO #006", accent: "#ccff44", hair: "#ddff88", eyes: "#ff44aa", skin: "#ffe8c8", traits: [{ t: "Hair", v: "Nine-Tail Flow" }, { t: "Eyes", v: "Fox Hetero" }, { t: "Outfit", v: "Spirit Kimono" }, { t: "Accessory", v: "Golden Bell" }, { t: "Bg", v: "Mystic Forest" }, { t: "Rarity", v: "Legendary" }] },
  { id: 6, name: "VOID RONIN #007", accent: "#aa66ff", hair: "#553388", eyes: "#ffffff", skin: "#c8b0a0", traits: [{ t: "Hair", v: "Long Black Topknot" }, { t: "Eyes", v: "Void White" }, { t: "Outfit", v: "Shadow Trench" }, { t: "Accessory", v: "Broken Mask" }, { t: "Bg", v: "Abandoned Temple" }, { t: "Rarity", v: "Epic" }] },
  { id: 7, name: "CYBER SAKI #008", accent: "#ff0088", hair: "#44ffff", eyes: "#ff0088", skin: "#f0d0b8", traits: [{ t: "Hair", v: "Holographic Bob" }, { t: "Eyes", v: "LED Pink" }, { t: "Outfit", v: "Chrome School Uniform" }, { t: "Accessory", v: "Data Gloves" }, { t: "Bg", v: "Shibuya Grid" }, { t: "Rarity", v: "Mythic" }] },
  { id: 8, name: "THUNDER YUKI #009", accent: "#66aaff", hair: "#ffffff", eyes: "#00ffff", skin: "#e8e8ff", traits: [{ t: "Hair", v: "Lightning Spikes" }, { t: "Eyes", v: "Electric Blue" }, { t: "Outfit", v: "Storm Jacket" }, { t: "Accessory", v: "Thunder Orb" }, { t: "Bg", v: "Lightning Sky" }, { t: "Rarity", v: "Legendary" }] },
  { id: 9, name: "GALAXY HARU #010", accent: "#cc88ff", hair: "#aa44ff", eyes: "#ffff88", skin: "#f8e0ff", traits: [{ t: "Hair", v: "Starry Twintails" }, { t: "Eyes", v: "Galaxy Swirl" }, { t: "Outfit", v: "Cosmic Hoodie" }, { t: "Accessory", v: "Nebula Earpiece" }, { t: "Bg", v: "Starfield" }, { t: "Rarity", v: "Epic" }] },
  { id: 10, name: "FLAME AKIRA #011", accent: "#ff5522", hair: "#ffaa44", eyes: "#ffee66", skin: "#f8c8a0", traits: [{ t: "Hair", v: "Fire Mohawk" }, { t: "Eyes", v: "Ember Glow" }, { t: "Outfit", v: "Racer Jacket" }, { t: "Accessory", v: "Flame Sunglasses" }, { t: "Bg", v: "Midnight Race" }, { t: "Rarity", v: "Mythic" }] },
  { id: 11, name: "CRYSTAL MIO #012", accent: "#44ffee", hair: "#88ffff", eyes: "#ff88ff", skin: "#f0ffff", traits: [{ t: "Hair", v: "Crystal Waves" }, { t: "Eyes", v: "Diamond Spark" }, { t: "Outfit", v: "Ice Princess Coat" }, { t: "Accessory", v: "Floating Crown" }, { t: "Bg", v: "Frozen Neon" }, { t: "Rarity", v: "Legendary" }] }
];
