export type Domain = "Tech" | "Business" | "Creative" | "Soft Skills";

export type Resource = {
  id: string;
  name: string;
  category: string;
  url: string;
  pricing: string;
  bestFor: string[];
  format: string;
  coverage: number;
  practice: number;
  structure: number;
  community: number;
  beginnerFit: number;
  depthLabel: string;
  timeToProficiency: string;
  strengths: string[];
  weaknesses: string[];
  notes: string;
};

export type ResearchInsight = {
  principle: string;
  summary: string;
  appliedToSkill: string;
};

export type RoadmapPhase = {
  label: string;
  days: string;
  focus: string;
  project: string;
  routine: string;
  checkpoint: string;
};

export type PrioritizationItem = {
  label: string;
  effort: number;
  impact: number;
  note: string;
};

export type LearningPath = {
  id: string;
  title: string;
  bundle: string[];
  bundleSummary: string;
  evidenceBasis: string;
  expectedOutcome: string;
  metrics: string[];
  roadmap: RoadmapPhase[];
};

export type SkillProfile = {
  slug: string;
  name: string;
  domain: Domain;
  tagline: string;
  overview: string;
  defaultPrompt: string;
  targetOutcome: string;
  keyQuestions: string[];
  relevantResourceIds: string[];
  researchInsights: ResearchInsight[];
  paths: LearningPath[];
  prioritization: PrioritizationItem[];
};

export const resources: Resource[] = [
  {
    id: "coursera-audit",
    name: "Coursera Audits",
    category: "MOOC",
    url: "https://www.coursera.org",
    pricing: "Free with audit mode",
    bestFor: ["structured foundations", "guided projects", "university-style sequencing"],
    format: "Video + quizzes + assignments",
    coverage: 90,
    practice: 70,
    structure: 94,
    community: 54,
    beginnerFit: 82,
    depthLabel: "High",
    timeToProficiency: "12-20 weeks with project work",
    strengths: ["Strong sequencing", "Wide catalog", "Credible academic structure"],
    weaknesses: ["Hands-on depth varies", "Some graded items are paywalled"],
    notes: "Works best when paired with projects and retrieval practice outside the platform.",
  },
  {
    id: "edx",
    name: "edX",
    category: "MOOC",
    url: "https://www.edx.org",
    pricing: "Free to audit many courses",
    bestFor: ["theory-heavy subjects", "technical depth", "business fundamentals"],
    format: "Lectures + assessments",
    coverage: 88,
    practice: 66,
    structure: 91,
    community: 40,
    beginnerFit: 74,
    depthLabel: "High",
    timeToProficiency: "14-22 weeks",
    strengths: ["Academic rigor", "Reliable syllabi", "Good technical breadth"],
    weaknesses: ["Less practice-centric", "Can feel lecture-heavy"],
    notes: "Useful when you want a stronger conceptual backbone before building projects.",
  },
  {
    id: "freecodecamp",
    name: "freeCodeCamp",
    category: "Bootcamp",
    url: "https://www.freecodecamp.org",
    pricing: "Free",
    bestFor: ["web development", "JavaScript", "portfolio building"],
    format: "Interactive exercises + projects",
    coverage: 86,
    practice: 96,
    structure: 88,
    community: 84,
    beginnerFit: 90,
    depthLabel: "High",
    timeToProficiency: "10-18 weeks",
    strengths: ["Hands-on curriculum", "Project cadence", "Large learner community"],
    weaknesses: ["Advanced depth needs supplementation", "Easy to progress too passively"],
    notes: "Excellent when visible output and practice density matter most.",
  },
  {
    id: "khan-academy",
    name: "Khan Academy",
    category: "Foundations",
    url: "https://www.khanacademy.org",
    pricing: "Free",
    bestFor: ["math repair", "statistics refreshers", "beginner confidence"],
    format: "Short lessons + practice",
    coverage: 72,
    practice: 85,
    structure: 86,
    community: 38,
    beginnerFit: 97,
    depthLabel: "Moderate",
    timeToProficiency: "6-12 weeks for prerequisite repair",
    strengths: ["Friendly explanations", "High repetition density", "Very beginner-accessible"],
    weaknesses: ["Limited advanced specialization", "Less career framing"],
    notes: "High-value support layer for technical skills that depend on shaky prerequisites.",
  },
  {
    id: "mit-ocw",
    name: "MIT OpenCourseWare",
    category: "University",
    url: "https://ocw.mit.edu",
    pricing: "Free",
    bestFor: ["deep theory", "engineering fundamentals", "algorithms"],
    format: "Lecture notes + videos + assignments",
    coverage: 92,
    practice: 78,
    structure: 80,
    community: 24,
    beginnerFit: 52,
    depthLabel: "Very high",
    timeToProficiency: "16-28 weeks",
    strengths: ["Exceptional rigor", "Original assignments", "Strong transfer value"],
    weaknesses: ["Steep ramp", "Minimal hand-holding"],
    notes: "Best after baseline fluency is established elsewhere.",
  },
  {
    id: "alison",
    name: "Alison",
    category: "Course Library",
    url: "https://alison.com",
    pricing: "Free learning access",
    bestFor: ["broad intros", "business skills", "entry-level upskilling"],
    format: "Self-paced modules",
    coverage: 70,
    practice: 54,
    structure: 75,
    community: 28,
    beginnerFit: 86,
    depthLabel: "Moderate",
    timeToProficiency: "8-14 weeks",
    strengths: ["Accessible pacing", "Wide catalog", "Low-friction starts"],
    weaknesses: ["Variable course quality", "Lighter project intensity"],
    notes: "Good for scouting a domain before committing to deeper resources.",
  },
  {
    id: "anthropic-academy",
    name: "Anthropic Academy",
    category: "AI",
    url: "https://www.anthropic.com/learn",
    pricing: "Free",
    bestFor: ["AI literacy", "prompt systems", "agent design"],
    format: "Guides + labs + examples",
    coverage: 76,
    practice: 72,
    structure: 68,
    community: 36,
    beginnerFit: 73,
    depthLabel: "Moderate",
    timeToProficiency: "4-8 weeks for applied workflows",
    strengths: ["Current applied framing", "Good systems thinking", "Useful examples"],
    weaknesses: ["Not a full curriculum", "Needs coding complements"],
    notes: "Strong for practical LLM workflows when paired with implementation practice.",
  },
  {
    id: "google-ai",
    name: "Grow with Google AI",
    category: "AI",
    url: "https://grow.google/ai",
    pricing: "Free",
    bestFor: ["AI productivity", "business AI", "intro AI fluency"],
    format: "Short courses + activities",
    coverage: 74,
    practice: 62,
    structure: 80,
    community: 32,
    beginnerFit: 88,
    depthLabel: "Moderate",
    timeToProficiency: "4-10 weeks",
    strengths: ["Pragmatic workflow focus", "Accessible language", "Good for non-technical learners"],
    weaknesses: ["Limited technical depth", "Needs external projects"],
    notes: "A strong front door for AI-adjacent roles and cross-functional teams.",
  },
  {
    id: "youtube",
    name: "YouTube Learning Channels",
    category: "Video",
    url: "https://www.youtube.com",
    pricing: "Free",
    bestFor: ["just-in-time explanations", "tool walkthroughs", "troubleshooting"],
    format: "Video playlists",
    coverage: 78,
    practice: 42,
    structure: 38,
    community: 64,
    beginnerFit: 83,
    depthLabel: "Variable",
    timeToProficiency: "Highly variable",
    strengths: ["Huge topical breadth", "Current tooling coverage", "Fast troubleshooting"],
    weaknesses: ["Inconsistent sequencing", "Easy to over-consume passively"],
    notes: "Best used as a tactical supplement, not the whole stack.",
  },
  {
    id: "brilliant",
    name: "Brilliant",
    category: "Interactive",
    url: "https://brilliant.org",
    pricing: "Free starter content",
    bestFor: ["quant reasoning", "problem-solving intuition", "math habits"],
    format: "Interactive problem paths",
    coverage: 68,
    practice: 88,
    structure: 77,
    community: 26,
    beginnerFit: 84,
    depthLabel: "Moderate",
    timeToProficiency: "6-10 weeks for reasoning gains",
    strengths: ["Active problem solving", "Short feedback loops", "Sticky learning design"],
    weaknesses: ["Limited free depth", "Less domain specificity"],
    notes: "Useful for strengthening the reasoning muscles behind technical skill growth.",
  },
  {
    id: "duolingo",
    name: "Duolingo",
    category: "Language",
    url: "https://www.duolingo.com",
    pricing: "Free tier",
    bestFor: ["language habit formation", "daily repetition", "vocabulary"],
    format: "Micro-lessons",
    coverage: 64,
    practice: 84,
    structure: 82,
    community: 34,
    beginnerFit: 95,
    depthLabel: "Moderate",
    timeToProficiency: "12-24 weeks for base fluency",
    strengths: ["High adherence design", "Daily habit support", "Low-friction repetition"],
    weaknesses: ["Weak speaking realism alone", "Needs conversation exposure"],
    notes: "A useful reference model for spaced repetition and habit design.",
  },
  {
    id: "harvard-csx",
    name: "Harvard CS50",
    category: "University",
    url: "https://cs50.harvard.edu",
    pricing: "Free",
    bestFor: ["computer science foundations", "problem solving", "intro programming"],
    format: "Lectures + labs + problem sets",
    coverage: 91,
    practice: 87,
    structure: 89,
    community: 80,
    beginnerFit: 71,
    depthLabel: "High",
    timeToProficiency: "10-16 weeks",
    strengths: ["Strong fundamentals", "Memorable assignments", "High trust"],
    weaknesses: ["Can feel intense", "Broad more than specialized"],
    notes: "A strong anchor for skill paths that depend on computational thinking.",
  },
  {
    id: "huggingface-course",
    name: "Hugging Face Course",
    category: "AI",
    url: "https://huggingface.co/learn",
    pricing: "Free",
    bestFor: ["LLMs", "transformers", "practical ML tooling"],
    format: "Docs-style course + notebooks",
    coverage: 84,
    practice: 79,
    structure: 70,
    community: 72,
    beginnerFit: 58,
    depthLabel: "High",
    timeToProficiency: "8-14 weeks",
    strengths: ["Current ecosystem relevance", "Practical code examples", "Open-source alignment"],
    weaknesses: ["Needs prior Python comfort", "Less pedagogy than mainstream courses"],
    notes: "Ideal second-stage resource after fundamentals are in place.",
  },
  {
    id: "scrimba",
    name: "Scrimba Free Tracks",
    category: "Interactive",
    url: "https://scrimba.com",
    pricing: "Free selected courses",
    bestFor: ["frontend dev", "JavaScript practice", "fast build loops"],
    format: "Interactive screencasts + coding",
    coverage: 78,
    practice: 90,
    structure: 82,
    community: 58,
    beginnerFit: 89,
    depthLabel: "Moderate",
    timeToProficiency: "8-14 weeks",
    strengths: ["Immediate edit-and-run feedback", "Project orientation", "Low friction"],
    weaknesses: ["Free tier is narrower", "Less coverage outside chosen tracks"],
    notes: "Great when you want faster action than standard video lessons allow.",
  },
  {
    id: "w3schools",
    name: "W3Schools",
    category: "Reference + Practice",
    url: "https://www.w3schools.com",
    pricing: "Free core learning access",
    bestFor: ["HTML/CSS/JS refreshers", "SQL syntax drills", "quick browser-based practice"],
    format: "Interactive examples + browser sandbox",
    coverage: 74,
    practice: 82,
    structure: 72,
    community: 46,
    beginnerFit: 94,
    depthLabel: "Moderate",
    timeToProficiency: "2-8 weeks as a fast reinforcement layer",
    strengths: ["Very accessible", "Instant runnable examples", "Strong refresher value"],
    weaknesses: ["Less rigorous than full curricula", "Limited depth for advanced engineering"],
    notes: "Best used as a verified quick-reference and practice layer alongside a deeper primary curriculum.",
  },
  {
    id: "hubspot-academy",
    name: "HubSpot Academy",
    category: "Business",
    url: "https://academy.hubspot.com",
    pricing: "Free",
    bestFor: ["product marketing", "content strategy", "customer communication"],
    format: "Short courses + templates",
    coverage: 71,
    practice: 56,
    structure: 79,
    community: 44,
    beginnerFit: 90,
    depthLabel: "Moderate",
    timeToProficiency: "5-10 weeks",
    strengths: ["Actionable frameworks", "Business tooling context", "Accessible for switchers"],
    weaknesses: ["More tactical than strategic", "Vendor-adjacent framing"],
    notes: "Helpful for product, PMM, and communication-heavy roles.",
  },
  {
    id: "toastmasters",
    name: "Toastmasters Resources",
    category: "Soft Skills",
    url: "https://www.toastmasters.org/resources",
    pricing: "Free public resources",
    bestFor: ["public speaking", "speech structure", "presentation confidence"],
    format: "Guides + exercises",
    coverage: 66,
    practice: 82,
    structure: 73,
    community: 78,
    beginnerFit: 88,
    depthLabel: "Moderate",
    timeToProficiency: "8-16 weeks with live practice",
    strengths: ["Built for repeated live reps", "Good feedback culture", "Concrete speaking frameworks"],
    weaknesses: ["Needs self-direction", "Best results need real audiences"],
    notes: "A valuable complement to any speaking or leadership path.",
  },
  {
    id: "opensap",
    name: "openSAP",
    category: "Business Tech",
    url: "https://open.sap.com",
    pricing: "Free",
    bestFor: ["product ops", "enterprise systems", "digital transformation"],
    format: "Structured online courses",
    coverage: 73,
    practice: 58,
    structure: 81,
    community: 30,
    beginnerFit: 70,
    depthLabel: "Moderate",
    timeToProficiency: "6-12 weeks",
    strengths: ["Process-oriented learning", "Enterprise framing", "Strong sequencing"],
    weaknesses: ["Narrower ecosystem", "Less useful for generalists alone"],
    notes: "Useful where product or operations work intersects with systems literacy.",
  },
  {
    id: "openlearn",
    name: "OpenLearn",
    category: "Open Education",
    url: "https://www.open.edu/openlearn",
    pricing: "Free",
    bestFor: ["broad humanities", "communication", "business refreshers"],
    format: "Article-style units + activities",
    coverage: 69,
    practice: 48,
    structure: 77,
    community: 22,
    beginnerFit: 91,
    depthLabel: "Moderate",
    timeToProficiency: "6-10 weeks",
    strengths: ["Low-pressure entry", "Strong explanations", "Useful breadth"],
    weaknesses: ["Less immersive practice", "Limited high-intensity projects"],
    notes: "A helpful source for conceptual refreshers and soft-skill context.",
  },
];

const buildRoadmap = (baseProject: string, intermediateProject: string, capstone: string): RoadmapPhase[] => [
  {
    label: "30 Days",
    days: "Days 1-30",
    focus: "Foundations, terminology, and first constrained reps",
    project: baseProject,
    routine: "5 study sessions weekly, 2 retrieval reviews, 1 reflection block",
    checkpoint: "Can explain core concepts from memory and complete a scoped beginner artifact",
  },
  {
    label: "60 Days",
    days: "Days 31-60",
    focus: "Applied workflows, feedback loops, and deliberate practice",
    project: intermediateProject,
    routine: "4 build or practice sessions, 1 peer review, 1 spaced recap loop",
    checkpoint: "Can complete an intermediate deliverable with documented tradeoffs",
  },
  {
    label: "90 Days",
    days: "Days 61-90",
    focus: "Portfolio evidence, complexity handling, and performance measurement",
    project: capstone,
    routine: "3 deep work blocks, 2 feedback iterations, weekly benchmark review",
    checkpoint: "Produces a portfolio-ready outcome with measurable quality indicators",
  },
];

const baseInsights = {
  deliberate: (summary: string, appliedToSkill: string): ResearchInsight => ({
    principle: "Deliberate Practice",
    summary,
    appliedToSkill,
  }),
  spaced: (summary: string, appliedToSkill: string): ResearchInsight => ({
    principle: "Spaced Retrieval",
    summary,
    appliedToSkill,
  }),
  interleaved: (summary: string, appliedToSkill: string): ResearchInsight => ({
    principle: "Interleaved Practice",
    summary,
    appliedToSkill,
  }),
};

const standardMetrics = {
  portfolio: ["2 public artifacts", "Weekly reflection log", "80% milestone adherence"],
  practice: ["12 focused reps", "1 peer or self review weekly", "1 capstone outcome metric"],
  communication: ["2 presentations or writeups", "Weekly explanation practice", "1 polished final deliverable"],
};

export const quickSelectSkills = [
  "Python Data Science",
  "Full-Stack Web Dev",
  "AI Engineering",
  "Product Management",
  "Public Speaking",
  "UX Design",
  "Cybersecurity",
  "Digital Marketing",
];

export const skills: SkillProfile[] = [
  {
    slug: "python-data-science",
    name: "Python Data Science",
    domain: "Tech",
    tagline: "Move from statistics refreshers to reproducible analysis and portfolio projects.",
    overview: "Emphasizes math repair, notebook fluency, practical analysis, and communication of findings.",
    defaultPrompt: "I want to become job-ready in Python data science using free resources, with strong focus on statistics, pandas, visualization, and portfolio projects.",
    targetOutcome: "Publish 2-3 analysis projects with clear business framing and reproducible notebooks.",
    keyQuestions: ["How strong are your math foundations?", "Do you need analytics, ML, or both?", "Can you produce portfolio evidence each month?"],
    relevantResourceIds: ["khan-academy", "coursera-audit", "edx", "freecodecamp", "mit-ocw", "youtube", "brilliant"],
    researchInsights: [
      baseInsights.deliberate("Focused drills on data cleaning, plotting, and statistical interpretation beat generic course completion.", "Run repeated notebook exercises where you explain each transformation and chart choice aloud."),
      baseInsights.spaced("Revisiting formulas and pandas operations across weeks improves transfer to real datasets.", "Use recall sessions on joins, groupby logic, distributions, and hypothesis testing."),
      baseInsights.interleaved("Alternating EDA, statistics, and storytelling improves flexible problem selection.", "Mix one coding session, one interpretation session, and one presentation session each week."),
    ],
    paths: [
      {
        id: "py-foundation",
        title: "Foundations First Analyst Stack",
        bundle: ["khan-academy", "coursera-audit", "freecodecamp"],
        bundleSummary: "Repair statistics, learn Python analysis patterns, then convert them into visible projects.",
        evidenceBasis: "Combines scaffolding, immediate practice, and retrieval cycles to reduce fragile understanding.",
        expectedOutcome: "Confident notebook-based analysis for real-world CSV and dashboard-style case studies.",
        metrics: ["2 completed notebooks", "1 statistics recall sheet per week", "80% project milestone adherence"],
        roadmap: buildRoadmap("Analyze a public dataset and explain five descriptive statistics in plain English.", "Build an EDA notebook with feature comparisons and clear visual annotations.", "Publish an end-to-end portfolio case study with data cleaning, analysis, and recommendations."),
      },
      {
        id: "py-rigorous",
        title: "Academic Core plus Applied Portfolio",
        bundle: ["mit-ocw", "edx", "youtube"],
        bundleSummary: "Use OCW and edX for theory depth, then YouTube tactically for tooling gaps.",
        evidenceBasis: "Deep conceptual models improve transfer when paired with contextual examples.",
        expectedOutcome: "Stronger reasoning on statistical decisions and better confidence in model assumptions.",
        metrics: ["3 assignment-grade writeups", "1 peer-reviewed notebook", "Weekly concept explanation journal"],
        roadmap: buildRoadmap("Complete probability and linear algebra refreshers with worked problem summaries.", "Rebuild a published analysis workflow from scratch using a new dataset.", "Deliver a rigorous capstone comparing multiple analytical approaches and documenting limitations."),
      },
      {
        id: "py-career",
        title: "Career Switcher Velocity Path",
        bundle: ["freecodecamp", "coursera-audit", "youtube"],
        bundleSummary: "Keep structure light, output high, and build visible progress every two weeks.",
        evidenceBasis: "Frequent visible wins improve persistence and reduce dropout during identity transition.",
        expectedOutcome: "A fast portfolio base with enough theory to discuss decisions credibly.",
        metrics: ["3 mini-projects", "Biweekly GitHub update", "Weekly feedback incorporation"],
        roadmap: buildRoadmap("Ship a mini data storytelling notebook using a familiar-industry dataset.", "Create an analysis with cleaning, segmentation, and chart-driven insights.", "Finish a portfolio package with README, visuals, and a short presentation deck."),
      },
      {
        id: "py-mastery",
        title: "Mastery Through Problem Solving",
        bundle: ["brilliant", "mit-ocw", "freecodecamp"],
        bundleSummary: "Train reasoning, strengthen fundamentals, and convert theory into artifacts.",
        evidenceBasis: "Problem-solving intensity supports retention when paired with project transfer.",
        expectedOutcome: "Higher confidence with unfamiliar analysis problems and stronger reasoning under constraints.",
        metrics: ["4 challenge writeups", "2 project retrospectives", "1 benchmarked capstone"],
        roadmap: buildRoadmap("Solve quant reasoning drills and document solution patterns.", "Implement analyses that require choosing and defending methods.", "Produce a capstone that compares baseline and improved approaches with reflective commentary."),
      },
    ],
    prioritization: [
      { label: "Statistics refresh", effort: 55, impact: 92, note: "Highest leverage if confidence is shaky." },
      { label: "Pandas drills", effort: 48, impact: 88, note: "Fast route to daily fluency." },
      { label: "Portfolio storytelling", effort: 62, impact: 84, note: "Critical for employability." },
      { label: "Advanced ML theory", effort: 82, impact: 58, note: "Delay until analysis basics are durable." },
    ],
  },
  {
    slug: "full-stack-web-dev",
    name: "Full-Stack Web Dev",
    domain: "Tech",
    tagline: "Blend frontend shipping speed with backend fundamentals and deployment habits.",
    overview: "Favors build frequency, system understanding, and portfolio proof over framework hype.",
    defaultPrompt: "Build me a free-resource path to become strong in full-stack web development with React, APIs, databases, and production habits.",
    targetOutcome: "Ship 3 portfolio apps with frontend, backend, auth, and deployment evidence.",
    keyQuestions: ["Do you already know JavaScript basics?", "Are you aiming for frontend-heavy or balanced roles?", "Can you deploy projects publicly every month?"],
    relevantResourceIds: ["freecodecamp", "scrimba", "w3schools", "coursera-audit", "harvard-csx", "youtube", "edx"],
    researchInsights: [
      baseInsights.deliberate("Practice complete user flows instead of isolated syntax.", "Build authentication, forms, CRUD, and deployment loops repeatedly with variation."),
      { principle: "Worked Example Fading", summary: "Start with guided builds, then remove support quickly.", appliedToSkill: "Clone a tutorial app once, then rebuild the same feature set from scratch." },
      baseInsights.interleaved("Alternating frontend and backend tasks prevents brittle specialization.", "Schedule weekly blocks for UI, API design, database modeling, and debugging."),
    ],
    paths: [
      {
        id: "fs-builder",
        title: "Builder's Momentum Stack",
        bundle: ["freecodecamp", "scrimba", "w3schools"],
        bundleSummary: "Maximize fast reps and convert every concept into a shippable feature.",
        evidenceBasis: "Short feedback loops improve persistence and practical transfer in code-heavy domains.",
        expectedOutcome: "Comfort building modern web apps with clear user flows and deployment habits.",
        metrics: ["3 shipped apps", "Weekly deployment", "Feature completion rate above 75%"],
        roadmap: buildRoadmap("Ship a responsive frontend with forms, state, and API fetching.", "Build a CRUD app with backend routes and hosted data.", "Launch a production-style app with auth, analytics, and polished UX."),
      },
      {
        id: "fs-rigorous",
        title: "Computer Science plus Product Builds",
        bundle: ["harvard-csx", "coursera-audit", "freecodecamp"],
        bundleSummary: "Use CS50 for foundations, then add structured web modules and practical projects.",
        evidenceBasis: "Foundational mental models reduce later fragility in architecture and debugging.",
        expectedOutcome: "Stronger problem-solving and cleaner reasoning about performance and structure.",
        metrics: ["1 algorithms review log", "2 architecture notes", "2 full-stack capstones"],
        roadmap: buildRoadmap("Master core programming concepts through problem sets and a small static app.", "Implement API-backed features and write architecture notes for each service boundary.", "Deliver a capstone with deployment, database schema, and user journey instrumentation."),
      },
      {
        id: "fs-career",
        title: "Career-Ready Portfolio Path",
        bundle: ["scrimba", "freecodecamp", "coursera-audit"],
        bundleSummary: "Balance guided learning with visible portfolio outcomes and interview-ready explanations.",
        evidenceBasis: "Visible artifact cadence increases motivation and employability signals.",
        expectedOutcome: "A balanced portfolio with enough depth to discuss engineering tradeoffs.",
        metrics: ["3 case-study READMEs", "Biweekly retrospective", "1 mock technical presentation"],
        roadmap: buildRoadmap("Build a polished marketing plus app shell with responsive UI and forms.", "Create a full-stack app with persistent data and role-based flows.", "Ship a final capstone and document architecture, metrics, and future roadmap."),
      },
      {
        id: "fs-structured",
        title: "Structured MOOC plus Tactical YouTube",
        bundle: ["coursera-audit", "edx", "youtube"],
        bundleSummary: "Stay disciplined with course sequencing and fill implementation gaps tactically.",
        evidenceBasis: "Structured sequencing improves coherence; tactical supplementation prevents stalling.",
        expectedOutcome: "A more disciplined and less scattered progression for self-directed learners.",
        metrics: ["Module completion consistency above 85%", "2 supplemental bug-fix logs", "1 polished final app"],
        roadmap: buildRoadmap("Complete core modules while implementing each week’s ideas in a mini app.", "Expand into backend and database integrations using guided assignments.", "Finish a capstone that mirrors a real production workflow and deployment setup."),
      },
    ],
    prioritization: [
      { label: "JavaScript fundamentals", effort: 52, impact: 94, note: "The best anti-fragility investment." },
      { label: "Deployment habit", effort: 40, impact: 82, note: "Keeps projects honest and demo-ready." },
      { label: "Database modeling", effort: 58, impact: 80, note: "Pays off in backend interviews." },
      { label: "CSS polish", effort: 34, impact: 61, note: "Useful, but lower leverage than shipping flows." },
    ],
  },
  {
    slug: "ai-engineering",
    name: "AI Engineering",
    domain: "Tech",
    tagline: "Blend AI system literacy, Python implementation, evaluation, and deployment realism.",
    overview: "Focuses on using models effectively, measuring results, and building workflows rather than only theory.",
    defaultPrompt: "I want a free-resource AI engineering path covering Python, LLM workflows, evaluation, retrieval, and portfolio projects.",
    targetOutcome: "Ship 2-3 applied AI systems with evaluation notes, prompt rationale, and implementation artifacts.",
    keyQuestions: ["Do you already know Python?", "Is your goal AI apps or deeper ML research?", "Can you evaluate outputs systematically?"],
    relevantResourceIds: ["anthropic-academy", "google-ai", "huggingface-course", "coursera-audit", "youtube", "freecodecamp"],
    researchInsights: [
      { principle: "Feedback Calibration", summary: "Skill improves faster when learners judge output quality against explicit rubrics.", appliedToSkill: "Track hallucination rate, relevance, latency, and user success on each prototype." },
      { principle: "Generation plus Evaluation", summary: "Creating systems and critiquing them together builds deeper competence than consuming examples alone.", appliedToSkill: "Build a simple agent or RAG app, then benchmark it weekly against failure cases." },
      baseInsights.spaced("Repeated recall of system patterns improves design transfer under pressure.", "Practice explaining embeddings, grounding, tool use, and eval loops from memory."),
    ],
    paths: [
      {
        id: "ai-applied",
        title: "Applied AI Systems Stack",
        bundle: ["anthropic-academy", "google-ai", "freecodecamp"],
        bundleSummary: "Get practical AI workflow concepts, then implement them in code with visible outputs.",
        evidenceBasis: "Concept-to-build transitions prevent shallow prompt-only understanding.",
        expectedOutcome: "Can build reliable AI productivity or assistant workflows with basic evaluation.",
        metrics: ["2 deployed prototypes", "Failure-case library", "Weekly evaluation scorecard"],
        roadmap: buildRoadmap("Build a prompt-and-tool workflow with explicit success criteria.", "Implement a retrieval or multi-step automation prototype and benchmark it.", "Ship a capstone AI app with evaluation logs, instrumentation, and a portfolio narrative."),
      },
      {
        id: "ai-open-source",
        title: "Open-Source LLM Builder",
        bundle: ["huggingface-course", "anthropic-academy", "youtube"],
        bundleSummary: "Pair open-source model tooling with current systems guidance and tactical implementation support.",
        evidenceBasis: "Varied examples plus direct coding practice accelerates applied transfer.",
        expectedOutcome: "Better fluency with modern AI tooling, workflows, and implementation tradeoffs.",
        metrics: ["3 notebook experiments", "2 eval comparisons", "1 architecture memo"],
        roadmap: buildRoadmap("Recreate core transformer workflow examples and annotate each step.", "Build an AI service with retrieval or tool invocation and compare prompt strategies.", "Deliver a polished system with evaluation metrics and a technical write-up."),
      },
      {
        id: "ai-rigorous",
        title: "Rigorous Foundations to AI Product Delivery",
        bundle: ["coursera-audit", "huggingface-course", "google-ai"],
        bundleSummary: "Start from solid ML framing, then climb into practical system delivery and user workflows.",
        evidenceBasis: "Foundational understanding improves debugging and system design decisions later.",
        expectedOutcome: "A balanced AI engineering profile that can explain both methods and product outcomes.",
        metrics: ["1 concept map", "2 evaluation dashboards", "1 capstone with user-facing metrics"],
        roadmap: buildRoadmap("Refresh ML and Python fundamentals while mapping system components.", "Prototype multiple AI workflows and document failure patterns.", "Ship a measurable AI assistant or automation with benchmarked outcomes."),
      },
      {
        id: "ai-speed",
        title: "Fast Portfolio AI Path",
        bundle: ["google-ai", "youtube", "freecodecamp"],
        bundleSummary: "Bias toward fast implementation and portfolio evidence while maintaining evaluation discipline.",
        evidenceBasis: "Frequent delivery supports motivation and faster external feedback.",
        expectedOutcome: "Strong public demos and practical AI implementation confidence.",
        metrics: ["3 demo videos", "2 public repos", "Weekly benchmark tracking"],
        roadmap: buildRoadmap("Ship an AI-powered workflow helper and measure before versus after productivity.", "Create a user-facing prototype with better prompting, guardrails, and UI.", "Publish a portfolio suite of AI builds with evaluation narratives and roadmaps."),
      },
    ],
    prioritization: [
      { label: "Evaluation design", effort: 58, impact: 95, note: "Core differentiator for serious AI builders." },
      { label: "Python implementation", effort: 63, impact: 90, note: "Needed to move past prompt-only workflows." },
      { label: "Prompt patterns", effort: 28, impact: 66, note: "Useful but insufficient alone." },
      { label: "ML theory depth", effort: 80, impact: 62, note: "Stage after working prototypes exist." },
    ],
  },
  {
    slug: "product-management",
    name: "Product Management",
    domain: "Business",
    tagline: "Build product judgment through customer thinking, prioritization, and execution routines.",
    overview: "Mixes frameworks, lightweight analytics, communication, and repeated decision practice.",
    defaultPrompt: "Help me build a free-resource product management learning path with strategy, prioritization, discovery, analytics, and communication.",
    targetOutcome: "Produce a strong PM portfolio with strategy docs, prioritization logic, and customer insight work.",
    keyQuestions: ["Are you moving from engineering, business, or operations?", "Do you need B2B, consumer, or platform PM framing?", "Can you practice writing and presenting weekly?"],
    relevantResourceIds: ["coursera-audit", "hubspot-academy", "openlearn", "google-ai", "youtube", "alison"],
    researchInsights: [
      { principle: "Case-Based Learning", summary: "Repeated product teardown and prioritization practice builds judgment faster than passive reading.", appliedToSkill: "Run weekly product critiques and write tradeoff memos from constrained scenarios." },
      { principle: "Reflection", summary: "Decision journals improve calibration and learning from outcomes.", appliedToSkill: "Track prediction, rationale, and post-hoc results for roadmap choices." },
      baseInsights.interleaved("Alternating user research, metrics, strategy, and communication improves transfer.", "Rotate between user problem framing, KPI review, roadmap writing, and presentation practice."),
    ],
    paths: [
      {
        id: "pm-core",
        title: "Core PM Judgment Stack",
        bundle: ["coursera-audit", "hubspot-academy", "youtube"],
        bundleSummary: "Blend structure, tactical business communication, and real-world product examples.",
        evidenceBasis: "Judgment forms faster when concepts are immediately applied to real products.",
        expectedOutcome: "Better prioritization, roadmap communication, and customer-centered framing.",
        metrics: ["6 teardown memos", "2 roadmap decks", "Weekly decision journal"],
        roadmap: buildRoadmap("Complete foundational PM modules and write weekly product critiques.", "Build discovery and prioritization artifacts for a chosen product area.", "Publish a capstone portfolio with PRD, KPI plan, and roadmap rationale."),
      },
      {
        id: "pm-ai",
        title: "AI-Era Product Manager Path",
        bundle: ["google-ai", "coursera-audit", "hubspot-academy"],
        bundleSummary: "Understand AI workflows and connect them to product discovery and value delivery.",
        evidenceBasis: "Cross-functional PMs benefit from translating technical capability into user outcomes.",
        expectedOutcome: "Stronger ability to shape AI-enabled products without overclaiming.",
        metrics: ["3 AI product critiques", "1 metrics framework", "1 launch narrative"],
        roadmap: buildRoadmap("Learn AI workflow basics and map opportunities in a target product.", "Write PM artifacts for an AI-enabled feature with clear constraints.", "Deliver an end-to-end case study with risk framing and adoption metrics."),
      },
      {
        id: "pm-switcher",
        title: "Career Switcher PM Architecture",
        bundle: ["alison", "openlearn", "youtube"],
        bundleSummary: "Start broad, strengthen language and frameworks, then move into decision-heavy practice.",
        evidenceBasis: "Lower-friction entry helps persistence before deeper strategic complexity.",
        expectedOutcome: "A practical PM starter toolkit with better confidence in interviews and cross-functional work.",
        metrics: ["4 artifact drafts", "2 mock stakeholder presentations", "Biweekly reflection notes"],
        roadmap: buildRoadmap("Survey product foundations and collect examples from products you use daily.", "Practice writing user stories, prioritization tradeoffs, and stakeholder updates.", "Publish a capstone portfolio package with roadmap and problem validation narrative."),
      },
      {
        id: "pm-rigorous",
        title: "Structured PM plus Analytics Path",
        bundle: ["coursera-audit", "openlearn", "google-ai"],
        bundleSummary: "Use structured courses for PM foundations and layer in analytical reasoning and AI-era workflows.",
        evidenceBasis: "A structured base helps prevent fragmented PM knowledge.",
        expectedOutcome: "Better synthesis across strategy, execution, and analytics.",
        metrics: ["1 KPI tree", "2 portfolio case studies", "1 final presentation"],
        roadmap: buildRoadmap("Build a PM concept map and baseline metrics vocabulary.", "Create customer and metrics artifacts for a real product scenario.", "Deliver a polished capstone linking opportunity sizing, roadmap, and measurement."),
      },
    ],
    prioritization: [
      { label: "Product teardown practice", effort: 36, impact: 91, note: "Fast route to stronger judgment." },
      { label: "Written communication", effort: 44, impact: 89, note: "PM leverage lives in clarity." },
      { label: "Analytics fluency", effort: 59, impact: 78, note: "Important, but not the only pillar." },
      { label: "Framework memorization", effort: 22, impact: 46, note: "Useful support, weak alone." },
    ],
  },
  {
    slug: "public-speaking",
    name: "Public Speaking",
    domain: "Soft Skills",
    tagline: "Build speaking confidence through repeated reps, feedback, and deliberate presentation design.",
    overview: "Uses retrieval, rehearsal, live reps, and reflective feedback rather than passive confidence advice.",
    defaultPrompt: "Create a free-resource public speaking path focused on confidence, speech structure, live practice, and measurable improvement.",
    targetOutcome: "Deliver confident, structured talks with clear openings, persuasive flow, and improved audience response.",
    keyQuestions: ["Do you fear live delivery, structure, or both?", "Can you record yourself weekly?", "Do you have access to real audiences?"],
    relevantResourceIds: ["toastmasters", "youtube", "coursera-audit", "openlearn", "alison"],
    researchInsights: [
      baseInsights.deliberate("Small repeated drills on openings, pauses, and transitions improve performance faster than whole-speech repetition alone.", "Train one speaking micro-skill per session and review recordings against a rubric."),
      { principle: "Exposure with Feedback", summary: "Gradual audience exposure plus specific feedback reduces avoidance and increases fluency.", appliedToSkill: "Move from self-recorded delivery to small groups to live presentations over 90 days." },
      baseInsights.spaced("Short frequent practice outperforms rare intense rehearsals.", "Use 10-15 minute speaking drills four times a week."),
    ],
    paths: [
      {
        id: "ps-live",
        title: "Live Practice Confidence Loop",
        bundle: ["toastmasters", "youtube", "openlearn"],
        bundleSummary: "Get structure from resources, then convert it into repeated live or recorded speaking reps.",
        evidenceBasis: "Performance skills grow fastest through feedback-rich repetition and gradual challenge increase.",
        expectedOutcome: "Noticeably calmer, clearer, and more persuasive delivery in professional settings.",
        metrics: ["12 recorded reps", "4 live audience reps", "Weekly self-rubric score"],
        roadmap: buildRoadmap("Write and record short speeches focused on openings and vocal clarity.", "Deliver structured 3-5 minute talks and collect feedback on pacing and confidence.", "Present a polished capstone talk with stronger audience engagement and message retention."),
      },
      {
        id: "ps-structured",
        title: "Structured Speaker's Foundation",
        bundle: ["coursera-audit", "toastmasters", "youtube"],
        bundleSummary: "Use guided frameworks for speech design and immediately stress-test them in delivery practice.",
        evidenceBasis: "Frameworks become useful only when converted into repeated retrieval and performance.",
        expectedOutcome: "More consistent speech structure and stronger story flow under pressure.",
        metrics: ["6 speech outlines", "3 peer reviews", "1 final presentation deck"],
        roadmap: buildRoadmap("Learn speech architecture and rehearse short message maps.", "Practice persuasive and explanatory talks with peer feedback loops.", "Deliver a final presentation with clear narrative flow, timing, and audience adaptation."),
      },
      {
        id: "ps-career",
        title: "Career Builder Speaking Path",
        bundle: ["alison", "youtube", "toastmasters"],
        bundleSummary: "Start with accessible materials, then move quickly into practical performance repetitions.",
        evidenceBasis: "Low-friction entry improves adherence for anxious or underpracticed speakers.",
        expectedOutcome: "A reliable communication base for interviews, meetings, and presentations.",
        metrics: ["10 short drills", "2 mock interview presentations", "Confidence rating improvement"],
        roadmap: buildRoadmap("Build a baseline speaking routine with short low-stakes recordings.", "Run realistic work-style presentations and adapt based on feedback.", "Finish with a confident capstone presentation and a clear improvement log."),
      },
      {
        id: "ps-story",
        title: "Story-Driven Presentation Path",
        bundle: ["youtube", "openlearn", "toastmasters"],
        bundleSummary: "Focus on narrative clarity, audience attention, and delivery mechanics together.",
        evidenceBasis: "Narrative structure improves recall and persuasiveness when paired with delivery drills.",
        expectedOutcome: "Better audience engagement and memorable presentations.",
        metrics: ["5 story-based outlines", "3 delivery retrospectives", "1 audience feedback summary"],
        roadmap: buildRoadmap("Practice story openings and concise takeaway framing.", "Deliver talks with stronger transitions and supporting examples.", "Present a capstone talk built around a clear narrative arc and strong close."),
      },
    ],
    prioritization: [
      { label: "Recorded reps", effort: 24, impact: 94, note: "Fastest way to reduce blind spots." },
      { label: "Live audience exposure", effort: 63, impact: 90, note: "High leverage after baseline comfort." },
      { label: "Speech structure drills", effort: 34, impact: 82, note: "Improves clarity quickly." },
      { label: "Reading more advice", effort: 18, impact: 28, note: "Weak substitute for reps." },
    ],
  },
  {
    slug: "ux-design",
    name: "UX Design",
    domain: "Creative",
    tagline: "Grow from interface instincts to research-backed design systems and case studies.",
    overview: "Centers on user flows, critique, iteration, and portfolio evidence rather than inspiration collection.",
    defaultPrompt: "Build me a free-resource UX design learning path with research, wireframing, visual design, and strong case studies.",
    targetOutcome: "Publish 2-3 UX case studies showing research, interaction reasoning, and iterative improvement.",
    keyQuestions: ["Do you need visual design strength, research skill, or both?", "Can you get feedback weekly?", "Do you already know any design tools?"],
    relevantResourceIds: ["coursera-audit", "youtube", "openlearn", "alison", "hubspot-academy"],
    researchInsights: [
      { principle: "Studio Critique", summary: "Regular critique improves judgment faster than solo polishing.", appliedToSkill: "Share low-fidelity wireframes early and revise based on specific usability goals." },
      { principle: "Worked Example Fading", summary: "Annotated examples help first, but rapid independent redesigns build true skill.", appliedToSkill: "Reverse-engineer one strong flow, then redesign a different product from scratch." },
      baseInsights.interleaved("Alternating research, layout, and writing produces more rounded case studies.", "Cycle between interview synthesis, wireframing, and rationale writing each week."),
    ],
    paths: [
      {
        id: "ux-case-study",
        title: "Portfolio Case Study Path",
        bundle: ["coursera-audit", "youtube", "openlearn"],
        bundleSummary: "Learn UX fundamentals, then convert every concept into a documented case-study artifact.",
        evidenceBasis: "Artifact-based learning produces stronger hiring signals and sharper judgment.",
        expectedOutcome: "A credible portfolio with research-backed design rationale.",
        metrics: ["2 full case studies", "Weekly critique log", "Usability findings incorporated"],
        roadmap: buildRoadmap("Complete core UX modules and redesign one simple user flow.", "Run lightweight research and iterate a higher-fidelity prototype.", "Publish a complete case study with process, outcomes, and next-step recommendations."),
      },
      {
        id: "ux-visual",
        title: "Visual Design plus UX Path",
        bundle: ["youtube", "alison", "coursera-audit"],
        bundleSummary: "Balance interface craft with UX process to avoid weak visuals or shallow reasoning.",
        evidenceBasis: "Combining theory and visual practice improves portfolio breadth.",
        expectedOutcome: "Better UI polish with clearer user-centered decisions.",
        metrics: ["3 interface redesigns", "2 rationale writeups", "1 systemized style guide"],
        roadmap: buildRoadmap("Practice layout, typography, and hierarchy through focused redesigns.", "Connect visual decisions to usability and user goals.", "Ship a polished case study with strong visual system and testing notes."),
      },
      {
        id: "ux-switcher",
        title: "Career Switcher UX Architecture",
        bundle: ["openlearn", "youtube", "hubspot-academy"],
        bundleSummary: "Start accessible, improve communication and audience thinking, then build UX artifacts.",
        evidenceBasis: "Cross-functional framing helps career switchers explain decisions convincingly.",
        expectedOutcome: "A strong starter portfolio with better storytelling and stakeholder framing.",
        metrics: ["2 mini case studies", "1 portfolio narrative", "Biweekly feedback cycles"],
        roadmap: buildRoadmap("Learn UX language and document the strengths and gaps of familiar products.", "Prototype and test one meaningful flow improvement.", "Publish a final case study with clear user problem, design decisions, and outcome measures."),
      },
      {
        id: "ux-research",
        title: "Research-Heavy UX Path",
        bundle: ["coursera-audit", "openlearn", "youtube"],
        bundleSummary: "Lean into user understanding, synthesis, and evidence-based iteration.",
        evidenceBasis: "Stronger problem framing leads to more credible and effective design work.",
        expectedOutcome: "Better interviews, synthesis, and decision quality in design projects.",
        metrics: ["3 interview summaries", "2 test reports", "1 research-first capstone"],
        roadmap: buildRoadmap("Learn user research basics and practice synthesizing small interview sets.", "Turn findings into flows, wireframes, and testable prototypes.", "Present a research-backed case study with iterative evidence and reflections."),
      },
    ],
    prioritization: [
      { label: "Weekly critique", effort: 38, impact: 90, note: "Biggest lever for design judgment." },
      { label: "Case study writing", effort: 46, impact: 85, note: "Turns work into trust." },
      { label: "Visual drills", effort: 42, impact: 72, note: "Important, especially for UI-heavy roles." },
      { label: "Tool memorization", effort: 20, impact: 34, note: "Secondary to design reasoning." },
    ],
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    domain: "Tech",
    tagline: "Build from networking and systems knowledge into practical defense habits and documented labs.",
    overview: "Values labs, threat reasoning, and structured systems understanding over certification-only study.",
    defaultPrompt: "Create a free-resource cybersecurity path with networking, systems basics, threat analysis, and practical labs.",
    targetOutcome: "Complete practical labs and produce a portfolio of security notes, analyses, and hardening projects.",
    keyQuestions: ["Do you already understand networking and OS basics?", "Are you aiming for blue team, general security, or app security?", "Can you practice in labs weekly?"],
    relevantResourceIds: ["coursera-audit", "edx", "youtube", "mit-ocw", "alison"],
    researchInsights: [
      { principle: "Scenario Practice", summary: "Threat recognition improves with varied realistic cases, not rote memorization alone.", appliedToSkill: "Analyze different attack paths and defensive responses weekly." },
      baseInsights.spaced("Explaining protocols and vulnerabilities from memory increases durable understanding.", "Use short whiteboard reviews on TCP/IP, auth models, and common weaknesses."),
      { principle: "Progressive Difficulty", summary: "Layering more complex labs prevents overload and improves confidence.", appliedToSkill: "Move from basic hardening tasks into multi-step detection and response scenarios." },
    ],
    paths: [
      {
        id: "cyber-core",
        title: "Security Foundations Stack",
        bundle: ["coursera-audit", "edx", "youtube"],
        bundleSummary: "Use structured theory for networking and systems, then reinforce it with practical walkthroughs.",
        evidenceBasis: "Security reasoning is stronger when conceptual systems models are well formed.",
        expectedOutcome: "A strong base for labs, interviews, and disciplined further specialization.",
        metrics: ["1 weekly threat memo", "2 hardened system exercises", "1 portfolio notebook"],
        roadmap: buildRoadmap("Refresh networking and operating system concepts with structured study.", "Complete guided hardening and monitoring exercises with documented observations.", "Produce a capstone analysis of a realistic threat scenario and defense plan."),
      },
      {
        id: "cyber-rigorous",
        title: "Rigorous Systems to Security Path",
        bundle: ["mit-ocw", "edx", "youtube"],
        bundleSummary: "Build deeper systems understanding, then connect it directly to security reasoning.",
        evidenceBasis: "Defensive intuition improves when underlying systems behavior is well understood.",
        expectedOutcome: "Stronger ability to reason about attacks, controls, and constraints.",
        metrics: ["Concept map updates", "Lab reflection journal", "1 final scenario response plan"],
        roadmap: buildRoadmap("Study systems concepts and produce summary diagrams from memory.", "Map common vulnerabilities to specific system behaviors and mitigations.", "Complete a capstone threat analysis with detection and response tradeoffs."),
      },
      {
        id: "cyber-practical",
        title: "Practical Security Build Path",
        bundle: ["youtube", "coursera-audit", "alison"],
        bundleSummary: "Bias toward accessible starts and regular hands-on reinforcement.",
        evidenceBasis: "Practical repetition improves persistence in a broad and intimidating domain.",
        expectedOutcome: "A more confident entry into security work with visible practice evidence.",
        metrics: ["10 short labs", "Weekly defense checklist", "1 hardening capstone"],
        roadmap: buildRoadmap("Start with security terminology and simple hardening steps.", "Build a repeatable lab routine and document failures and fixes.", "Publish a capstone environment hardening and analysis report."),
      },
      {
        id: "cyber-balanced",
        title: "Balanced Career Builder Security Path",
        bundle: ["coursera-audit", "youtube", "mit-ocw"],
        bundleSummary: "Blend employable practicals with deeper systems literacy.",
        evidenceBasis: "Balanced paths help avoid shallow tooling dependence.",
        expectedOutcome: "A better base for junior cybersecurity, IT security, or adjacent technical roles.",
        metrics: ["2 project artifacts", "1 technical presentation", "Weekly recall review"],
        roadmap: buildRoadmap("Build systems fluency and security vocabulary in parallel.", "Run practical labs and explain the reasoning behind each step.", "Deliver a capstone project and presentation that shows layered understanding."),
      },
    ],
    prioritization: [
      { label: "Networking fundamentals", effort: 52, impact: 93, note: "Critical for nearly every security path." },
      { label: "Hands-on labs", effort: 64, impact: 91, note: "Turns concepts into operational skill." },
      { label: "Threat memo writing", effort: 28, impact: 70, note: "Sharpens analytical communication." },
      { label: "Tool collecting", effort: 19, impact: 30, note: "Low value without strong foundations." },
    ],
  },
  {
    slug: "data-analysis",
    name: "Data Analysis",
    domain: "Business",
    tagline: "Strengthen spreadsheet, SQL, and interpretation skills to produce reliable business insight.",
    overview: "Focuses on turning data into decisions, not only using tools.",
    defaultPrompt: "Build me a free-resource data analysis path covering spreadsheets, SQL, dashboards, and communicating business insight.",
    targetOutcome: "Deliver dashboard-ready analyses and concise business recommendations with evidence.",
    keyQuestions: ["Do you need spreadsheet, SQL, or Python emphasis?", "Is your target business, operations, or product analytics?", "Can you work with public datasets weekly?"],
    relevantResourceIds: ["coursera-audit", "google-ai", "khan-academy", "youtube", "alison", "openlearn"],
    researchInsights: [
      { principle: "Worked Problems", summary: "Stepping through concrete business questions builds analytical judgment faster than abstract theory alone.", appliedToSkill: "Use weekly prompts that force segmentation, trend reading, and recommendation writing." },
      { principle: "Dual Coding", summary: "Combining numeric analysis with visual explanation improves retention and communication.", appliedToSkill: "Translate each analysis into one concise chart and one written insight summary." },
      baseInsights.spaced("Frequent recall of formulas and analytical patterns improves speed and transfer.", "Review common metrics, SQL patterns, and chart selection principles weekly."),
    ],
    paths: [
      {
        id: "da-business",
        title: "Business Analyst Core Stack",
        bundle: ["coursera-audit", "youtube", "openlearn"],
        bundleSummary: "Use structure for fundamentals and convert each lesson into business-style analysis artifacts.",
        evidenceBasis: "Decision-oriented application improves retention and portfolio value.",
        expectedOutcome: "Can answer practical business questions with appropriate metrics and clarity.",
        metrics: ["2 dashboard analyses", "Weekly insight memo", "1 capstone recommendation deck"],
        roadmap: buildRoadmap("Refresh metrics and core analysis concepts using business examples.", "Create analyses that combine trends, comparisons, and concise recommendations.", "Publish a capstone with dashboard outputs and an executive-style summary."),
      },
      {
        id: "da-quant",
        title: "Quant Foundations plus Applied Analysis",
        bundle: ["khan-academy", "coursera-audit", "youtube"],
        bundleSummary: "Repair math confidence, then build analysis habits on top of stronger quantitative reasoning.",
        evidenceBasis: "Improved prerequisite fluency reduces interpretation mistakes later.",
        expectedOutcome: "Better confidence with metrics, distributions, and analytical tradeoffs.",
        metrics: ["Statistics recall score", "2 case analyses", "1 final capstone"],
        roadmap: buildRoadmap("Repair statistics basics and explain common metrics from memory.", "Use those foundations in practical analyses with increasing ambiguity.", "Deliver a capstone that compares scenarios and justifies recommendations."),
      },
      {
        id: "da-speed",
        title: "Fast Evidence Portfolio Path",
        bundle: ["youtube", "google-ai", "coursera-audit"],
        bundleSummary: "Keep the path practical and output-heavy while using AI tools to accelerate iteration.",
        evidenceBasis: "Visible outputs and lighter support tooling increase consistency for self-directed learners.",
        expectedOutcome: "A quick portfolio base with credible analysis and stronger communication.",
        metrics: ["3 mini analyses", "2 presentation summaries", "Weekly chart review"],
        roadmap: buildRoadmap("Produce short analyses with clean chart selection and written takeaways.", "Expand into more ambiguous business datasets and compare alternative views.", "Package your best analysis into a polished portfolio case study."),
      },
      {
        id: "da-structured",
        title: "Structured Survey to Specialization",
        bundle: ["alison", "coursera-audit", "openlearn"],
        bundleSummary: "Start broad, then narrow toward business-ready analytical practice.",
        evidenceBasis: "Survey learning lowers friction while still enabling later specialization.",
        expectedOutcome: "A coherent understanding of where to focus next and a solid analysis base.",
        metrics: ["Learning map", "2 project artifacts", "1 final recommendation brief"],
        roadmap: buildRoadmap("Survey the landscape and identify target analytical contexts.", "Develop repeatable workflows for cleaning, analysis, and communication.", "Finish with a capstone that shows end-to-end analytical thinking."),
      },
    ],
    prioritization: [
      { label: "Metric interpretation", effort: 34, impact: 93, note: "Core to trustworthy analysis." },
      { label: "Chart selection", effort: 29, impact: 76, note: "Useful for clarity and decision support." },
      { label: "Statistics repair", effort: 54, impact: 84, note: "High leverage if rusty." },
      { label: "Tool hopping", effort: 23, impact: 27, note: "Often a distraction early on." },
    ],
  },
  {
    slug: "digital-marketing",
    name: "Digital Marketing",
    domain: "Business",
    tagline: "Connect messaging, channels, experimentation, and metrics into repeatable growth work.",
    overview: "Emphasizes execution and measurement over trend chasing.",
    defaultPrompt: "Build me a free-resource digital marketing path covering content, SEO, campaigns, analytics, and experimentation.",
    targetOutcome: "Produce campaign plans, channel experiments, and measurable growth case studies.",
    keyQuestions: ["Do you care most about content, paid growth, SEO, or lifecycle?", "Can you run small experiments on your own projects?", "Are you optimizing for freelance work, jobs, or internal roles?"],
    relevantResourceIds: ["hubspot-academy", "google-ai", "coursera-audit", "youtube", "alison", "openlearn"],
    researchInsights: [
      { principle: "Feedback Loops", summary: "Marketers improve faster when they connect actions to observed channel outcomes.", appliedToSkill: "Track hypotheses, campaign choices, and result changes in a simple experiment log." },
      { principle: "Case Comparison", summary: "Comparing campaigns across contexts sharpens channel judgment.", appliedToSkill: "Review examples and write why a tactic worked, failed, or would need adaptation." },
      baseInsights.spaced("Revisiting core frameworks improves speed in planning and critique.", "Recall funnel, audience, and messaging frameworks weekly without notes."),
    ],
    paths: [
      {
        id: "dm-practical",
        title: "Practical Growth Stack",
        bundle: ["hubspot-academy", "youtube", "google-ai"],
        bundleSummary: "Learn channel logic, then apply it through small experiments and AI-assisted execution.",
        evidenceBasis: "Execution plus measurement beats theory-only familiarity in fast-moving domains.",
        expectedOutcome: "A solid foundation for campaign design, analysis, and storytelling.",
        metrics: ["3 campaign briefs", "Experiment log", "1 measurable growth case study"],
        roadmap: buildRoadmap("Learn core channel and content frameworks, then map them to one target audience.", "Run small campaigns or simulations with clear hypotheses and metrics.", "Publish a capstone case study with results, insights, and next-step recommendations."),
      },
      {
        id: "dm-structured",
        title: "Structured Marketing Foundations",
        bundle: ["coursera-audit", "hubspot-academy", "openlearn"],
        bundleSummary: "Use structured theory to avoid fragmentation, then add tactical channel work.",
        evidenceBasis: "Clear foundational models help learners adapt as platforms change.",
        expectedOutcome: "More strategic reasoning and stronger campaign planning.",
        metrics: ["2 strategy decks", "Weekly channel notes", "1 final portfolio artifact"],
        roadmap: buildRoadmap("Learn segmentation, positioning, and messaging fundamentals.", "Translate those concepts into campaign briefs and channel-specific plans.", "Produce a capstone growth plan with funnel logic and outcome metrics."),
      },
      {
        id: "dm-switcher",
        title: "Career Switcher Marketing Path",
        bundle: ["alison", "hubspot-academy", "youtube"],
        bundleSummary: "Start with accessible foundations, then build practical campaign artifacts quickly.",
        evidenceBasis: "Lower-friction starts improve adherence for career changers.",
        expectedOutcome: "A visible starter portfolio and better confidence in growth conversations.",
        metrics: ["2 campaign mockups", "1 experiment summary", "Biweekly reflection log"],
        roadmap: buildRoadmap("Survey core marketing concepts and collect strong campaign examples.", "Create simple channel plans and test message variations.", "Finish with a portfolio-ready campaign case study and performance narrative."),
      },
      {
        id: "dm-analytics",
        title: "Analytics-Aware Marketing Path",
        bundle: ["google-ai", "coursera-audit", "youtube"],
        bundleSummary: "Prioritize measurement, workflow leverage, and interpretation alongside marketing craft.",
        evidenceBasis: "Measurement literacy makes marketers more adaptable and credible.",
        expectedOutcome: "Stronger ability to connect creative choices with business outcomes.",
        metrics: ["KPI dashboard draft", "2 performance readouts", "1 capstone analysis"],
        roadmap: buildRoadmap("Learn core marketing metrics and workflow tools.", "Run channel experiments and document what the numbers imply.", "Deliver a capstone that blends campaign design with analytical evaluation."),
      },
    ],
    prioritization: [
      { label: "Experiment tracking", effort: 32, impact: 92, note: "Builds real growth intuition." },
      { label: "Audience and messaging", effort: 41, impact: 88, note: "The strategic core of channel execution." },
      { label: "Analytics fluency", effort: 54, impact: 79, note: "Important for attribution and decision quality." },
      { label: "Trend chasing", effort: 18, impact: 21, note: "Low durability." },
    ],
  },
  {
    slug: "technical-writing",
    name: "Technical Writing",
    domain: "Creative",
    tagline: "Turn complex systems into clear explanations through deliberate structure and audience-aware drafts.",
    overview: "Emphasizes explanation quality, information architecture, and revision under feedback.",
    defaultPrompt: "Build me a free-resource technical writing path with documentation, tutorials, clarity, and portfolio pieces.",
    targetOutcome: "Publish a documentation portfolio that demonstrates clarity, structure, and technical audience awareness.",
    keyQuestions: ["Are you writing for developers, users, or mixed audiences?", "Do you already have a technical domain to write about?", "Can you revise based on feedback?"],
    relevantResourceIds: ["openlearn", "coursera-audit", "youtube", "hubspot-academy", "alison"],
    researchInsights: [
      { principle: "Audience Calibration", summary: "Writers improve faster when they test drafts against reader needs and misconceptions.", appliedToSkill: "Define audience, prerequisites, and likely friction before each tutorial or guide." },
      { principle: "Revision with Feedback", summary: "Quality rises through targeted revision, not first-draft intensity.", appliedToSkill: "Review structure, example clarity, and scannability in separate passes." },
      { principle: "Worked Example plus Transfer", summary: "Studying strong documentation helps, but writing across contexts builds durable skill.", appliedToSkill: "Alternate between API docs, tutorials, and concept guides." },
    ],
    paths: [
      {
        id: "tw-docs",
        title: "Documentation Portfolio Stack",
        bundle: ["openlearn", "coursera-audit", "youtube"],
        bundleSummary: "Learn clear writing principles, then convert them into progressively better documentation pieces.",
        evidenceBasis: "Frequent drafting and revision are the main growth engine in writing skills.",
        expectedOutcome: "A stronger public writing portfolio with better structure and usefulness.",
        metrics: ["4 polished docs pieces", "Revision checklist completion", "Reader feedback incorporated"],
        roadmap: buildRoadmap("Study clarity and structure fundamentals, then rewrite weak docs examples.", "Create tutorials and concept guides with stronger audience targeting.", "Publish a capstone portfolio set with before and after revisions and rationale."),
      },
      {
        id: "tw-product",
        title: "Product and Support Writing Path",
        bundle: ["hubspot-academy", "openlearn", "youtube"],
        bundleSummary: "Blend technical explanation with user-centered messaging and support clarity.",
        evidenceBasis: "Audience empathy improves adoption and comprehension.",
        expectedOutcome: "Stronger docs for onboarding, support, and user enablement.",
        metrics: ["2 help center drafts", "2 onboarding guides", "1 final docs case study"],
        roadmap: buildRoadmap("Map audiences and write concise support-oriented content.", "Develop user-facing tutorials and troubleshooting guides.", "Deliver a capstone package that shows clear IA and improved user comprehension."),
      },
      {
        id: "tw-switcher",
        title: "Career Switcher Writing Architecture",
        bundle: ["alison", "openlearn", "coursera-audit"],
        bundleSummary: "Use accessible learning to build writing discipline, then deepen structure and technical specificity.",
        evidenceBasis: "Gradual complexity keeps momentum high for new technical communicators.",
        expectedOutcome: "A credible early portfolio and clearer writing process.",
        metrics: ["3 writing samples", "Feedback log", "1 polished final guide"],
        roadmap: buildRoadmap("Build core writing habits and documentation awareness.", "Draft increasingly technical content with audience-specific framing.", "Publish a final guide set with revision notes and usability improvements."),
      },
      {
        id: "tw-rigorous",
        title: "Structured Clarity and Revision Path",
        bundle: ["coursera-audit", "openlearn", "youtube"],
        bundleSummary: "Use structure for theory and tactical examples to improve applied execution.",
        evidenceBasis: "Separated revision passes improve quality more than generic proofreading.",
        expectedOutcome: "Sharper writing process and stronger explanatory precision.",
        metrics: ["Checklist adherence", "3 iterative revisions", "1 comprehensive capstone"],
        roadmap: buildRoadmap("Learn documentation principles and apply them to short guides.", "Practice tutorial writing and modular content architecture.", "Deliver a capstone docs package with measurable improvements in readability and clarity."),
      },
    ],
    prioritization: [
      { label: "Revision cycles", effort: 36, impact: 93, note: "Biggest quality multiplier." },
      { label: "Audience analysis", effort: 31, impact: 88, note: "Prevents vague writing." },
      { label: "Tutorial building", effort: 45, impact: 79, note: "High-value portfolio format." },
      { label: "Style trivia", effort: 18, impact: 30, note: "Low leverage without strong structure." },
    ],
  },
  {
    slug: "sql-analytics",
    name: "SQL Analytics",
    domain: "Tech",
    tagline: "Build trustworthy query habits, metric fluency, and business interpretation through repeated analysis.",
    overview: "Emphasizes query reasoning and business communication, not just syntax memorization.",
    defaultPrompt: "Create a free-resource SQL analytics path with query skills, metrics, case studies, and reporting clarity.",
    targetOutcome: "Produce business-ready analyses using SQL patterns, validation habits, and concise reporting.",
    keyQuestions: ["Are you starting from zero SQL?", "Do you need analyst-style SQL or deeper engineering patterns?", "Can you practice query validation weekly?"],
    relevantResourceIds: ["coursera-audit", "youtube", "freecodecamp", "w3schools", "openlearn", "google-ai"],
    researchInsights: [
      baseInsights.spaced("Actively reconstructing query patterns improves speed and accuracy under pressure.", "Review joins, window logic, and aggregation patterns from memory before writing them."),
      { principle: "Error-Based Learning", summary: "Studying mistakes and failed queries makes patterns more durable.", appliedToSkill: "Keep a query bug log with reasoning for each fix." },
      { principle: "Contextual Application", summary: "Query skill transfers best when tied to realistic business questions.", appliedToSkill: "Write queries that answer product, marketing, or operations questions every week." },
    ],
    paths: [
      {
        id: "sql-core",
        title: "Business SQL Core",
        bundle: ["coursera-audit", "youtube", "openlearn"],
        bundleSummary: "Use structured SQL lessons, then apply them immediately to business-style questions.",
        evidenceBasis: "Context-rich practice strengthens transfer better than isolated syntax drills.",
        expectedOutcome: "Confident use of SQL for reporting, segmentation, and trend analysis.",
        metrics: ["20 query reps", "Weekly bug log", "1 capstone analysis deck"],
        roadmap: buildRoadmap("Learn core query patterns and validate them on simple datasets.", "Answer realistic business questions with increasingly complex joins and aggregations.", "Deliver a capstone with query-backed insights and stakeholder-facing summaries."),
      },
      {
        id: "sql-practical",
        title: "Practical Query Builder Path",
        bundle: ["freecodecamp", "w3schools", "youtube"],
        bundleSummary: "Bias toward repetition, troubleshooting, and fast transfer into business questions.",
        evidenceBasis: "Frequent feedback loops improve fluency faster in rule-based skills.",
        expectedOutcome: "Better query speed, debugging confidence, and practical analysis delivery.",
        metrics: ["30 timed query drills", "2 mini case studies", "1 final portfolio artifact"],
        roadmap: buildRoadmap("Run foundational drill sets and explain each query in plain language.", "Use SQL to answer funnel, retention, or segmentation prompts.", "Publish a final case study with query reasoning, checks, and recommendations."),
      },
      {
        id: "sql-structured",
        title: "Structured SQL to Analytics Path",
        bundle: ["coursera-audit", "freecodecamp", "youtube"],
        bundleSummary: "Combine formal sequencing with larger volumes of practical reps.",
        evidenceBasis: "Blending sequence and repetition gives both coherence and fluency.",
        expectedOutcome: "A reliable SQL analysis skillset with stronger explanatory confidence.",
        metrics: ["Module pace above 85%", "Query validation checklist", "2 portfolio analyses"],
        roadmap: buildRoadmap("Build query fundamentals and document common validation steps.", "Practice intermediate analysis patterns and explain tradeoffs.", "Ship a capstone analysis with clear SQL logic and stakeholder-friendly outputs."),
      },
      {
        id: "sql-speed",
        title: "Fast Portfolio SQL Path",
        bundle: ["youtube", "google-ai", "coursera-audit"],
        bundleSummary: "Keep the path light and output-heavy, using support tools to accelerate practice.",
        evidenceBasis: "Visible progress and lower friction support consistency.",
        expectedOutcome: "A quick portfolio entry point with practical query competence.",
        metrics: ["2 mini reports", "1 final dashboard case", "Weekly recall sessions"],
        roadmap: buildRoadmap("Practice query patterns with short real-world prompts.", "Translate SQL results into clear business summaries.", "Package the best work into a capstone report and presentation."),
      },
    ],
    prioritization: [
      { label: "Join and aggregation fluency", effort: 46, impact: 94, note: "Primary engine of useful SQL." },
      { label: "Query validation", effort: 28, impact: 86, note: "Builds trustworthiness fast." },
      { label: "Business framing", effort: 40, impact: 80, note: "Essential for analyst roles." },
      { label: "Rare advanced syntax", effort: 57, impact: 42, note: "Later-stage specialization." },
    ],
  },
  {
    slug: "project-management",
    name: "Project Management",
    domain: "Business",
    tagline: "Build execution reliability through planning, communication, risk control, and retrospectives.",
    overview: "Develops operational clarity and follow-through rather than only terminology.",
    defaultPrompt: "Help me build a free-resource project management path with planning, execution, stakeholder communication, and measurable outcomes.",
    targetOutcome: "Run scoped projects with clearer plans, communication, and measurable delivery rhythm.",
    keyQuestions: ["Are you managing technical, operations, or cross-functional projects?", "Do you need formal frameworks or practical execution first?", "Can you practice on real or simulated projects now?"],
    relevantResourceIds: ["coursera-audit", "alison", "openlearn", "hubspot-academy", "youtube"],
    researchInsights: [
      { principle: "Reflection and Retrospective", summary: "Regular retrospectives improve forecasting and execution quality.", appliedToSkill: "Review what slipped, why it slipped, and what process change follows each week." },
      { principle: "Scenario Planning", summary: "Exposure to multiple project failure modes builds better risk judgment.", appliedToSkill: "Run weekly exercises on scope, dependency, and stakeholder misalignment cases." },
      { principle: "Deliberate Communication Practice", summary: "Managing projects requires repeated updates, not just planning templates.", appliedToSkill: "Write concise status updates and escalation notes every week." },
    ],
    paths: [
      {
        id: "pmgmt-core",
        title: "Operational Reliability Stack",
        bundle: ["coursera-audit", "openlearn", "youtube"],
        bundleSummary: "Use structured planning concepts, then rehearse execution with repeated project artifacts.",
        evidenceBasis: "Execution skill grows through planning-feedback-retrospective loops.",
        expectedOutcome: "Stronger delivery rhythm and clearer stakeholder communication.",
        metrics: ["Weekly status notes", "2 project plans", "1 final capstone retrospective"],
        roadmap: buildRoadmap("Learn planning basics and draft a project charter plus timeline.", "Practice risks, dependencies, and communication on a simulated or real project.", "Deliver a capstone project package with outcomes, lessons, and next-step process improvements."),
      },
      {
        id: "pmgmt-practical",
        title: "Practical PM Career Builder",
        bundle: ["alison", "coursera-audit", "hubspot-academy"],
        bundleSummary: "Start accessible, then strengthen communication and cross-functional execution habits.",
        evidenceBasis: "Accessible entry points improve consistency while communication practice sharpens readiness.",
        expectedOutcome: "Better readiness for coordinator, operations, or PM-style delivery roles.",
        metrics: ["2 artifact sets", "1 stakeholder communication deck", "Biweekly retrospective"],
        roadmap: buildRoadmap("Survey the PM landscape and create basic planning artifacts.", "Run a project workflow with updates, risk management, and change handling.", "Publish a final capstone showing execution discipline and learning maturity."),
      },
      {
        id: "pmgmt-structured",
        title: "Structured Frameworks to Delivery",
        bundle: ["coursera-audit", "youtube", "openlearn"],
        bundleSummary: "Maintain structure while using tactical examples to make frameworks concrete.",
        evidenceBasis: "Sequenced theory improves coherence when immediately tested in scenarios.",
        expectedOutcome: "Stronger confidence applying PM frameworks rather than merely naming them.",
        metrics: ["Framework application journal", "2 communication plans", "1 final project review"],
        roadmap: buildRoadmap("Learn core PM frameworks and map them to simple projects.", "Practice stakeholder, scope, and schedule management in realistic cases.", "Deliver a final project package with tradeoffs, results, and process improvements."),
      },
      {
        id: "pmgmt-comms",
        title: "Stakeholder Communication-Focused Path",
        bundle: ["hubspot-academy", "openlearn", "youtube"],
        bundleSummary: "Improve the communication layer that often determines perceived PM strength.",
        evidenceBasis: "Clear communication improves coordination and execution trust.",
        expectedOutcome: "Sharper updates, meetings, and escalation handling in project environments.",
        metrics: ["6 status updates", "2 meeting templates", "1 presentation capstone"],
        roadmap: buildRoadmap("Practice concise updates and stakeholder-aware messaging.", "Manage realistic project scenarios through communication artifacts.", "Finish with a capstone delivery review and stakeholder presentation."),
      },
    ],
    prioritization: [
      { label: "Retrospective habit", effort: 24, impact: 88, note: "Improves forecasting and reliability fast." },
      { label: "Status communication", effort: 31, impact: 90, note: "High-leverage project signal." },
      { label: "Risk planning", effort: 43, impact: 82, note: "Important for more complex delivery." },
      { label: "Template collecting", effort: 17, impact: 25, note: "Useful only when applied." },
    ],
  },
];

export function slugifySkillName(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

export function getSkillBySlug(slug: string | null) {
  if (!slug) return null;
  return skills.find((skill) => skill.slug === slug) ?? null;
}

export function getSkillByName(name: string) {
  return getSkillBySlug(slugifySkillName(name));
}

export function getResourcesForSkill(skill: SkillProfile) {
  return skill.relevantResourceIds
    .map((id) => resources.find((resource) => resource.id === id))
    .filter((resource): resource is Resource => Boolean(resource));
}
